version: "3.3"
services:

    # PHP service
    app:
        build: .
        container_name: php-app
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app-network

    # MySQL database service
    db:
        image: mysql:5.7
        container_name: mysql-db
        ports:
            - "3306:3306"
        volumes:
            - ./lmszai.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: lmszai
            MYSQL_USER: lmszai
            MYSQL_PASSWORD: 123456
        env_file:
            - ./.env
        networks:
            - app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
